"""
seal.py — tamper-evident SHA256 seal for a recorded mission session.

After a session folder is populated and compressed, write_seal() hashes the
key artefacts and writes two files into the session directory:

  seal.json  — machine-readable (for programmatic verification)
  seal.txt   — human-readable (for quick visual inspection)

The session-directory hash covers every file whose name is not in
*exclude_names* so the seal itself is not part of what it covers.
The summary is also excluded because it is a derived view — all raw
data is covered by manifest_sha256 and session_directory_sha256.

Stdlib only — no external dependencies.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

SEAL_VERSION = "0.2"

# Files generated by the sealing step or from derived data.
# Excluding them from the directory hash avoids a circular dependency
# and keeps the hash stable across any future summary regeneration.
_DIR_HASH_EXCLUDE = {
    "seal.json",
    "seal.txt",
    "seal_card.md",
    "seal_payload.json",
    "mission_summary.md",
}


# ── Core hash helpers ─────────────────────────────────────────────────────────

def sha256_file(path: Path) -> str:
    """Return the lowercase hex SHA256 digest of a file's raw bytes."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65_536), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_text(text: str) -> str:
    """Return the lowercase hex SHA256 digest of a UTF-8 encoded string."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sha256_directory(path: Path, exclude_names: set[str] | None = None) -> str:
    """Return a single SHA256 digest that covers every file in *path*.

    Files are processed in deterministic sorted order (by POSIX relative path).
    Each file contributes ``"relative/path:file_sha256\\n"`` to the outer hash,
    so both filenames and contents are covered.

    Parameters
    ----------
    path:           Directory to hash recursively.
    exclude_names:  Set of bare filenames (not paths) to skip, e.g.
                    ``{"seal.json", "seal.txt"}``.
    """
    skip = (exclude_names or set()) | _DIR_HASH_EXCLUDE
    h = hashlib.sha256()
    for file in sorted(path.rglob("*")):
        if not file.is_file():
            continue
        if file.name in skip:
            continue
        rel = file.relative_to(path).as_posix()   # forward slashes on all platforms
        file_hash = sha256_file(file)
        h.update(f"{rel}:{file_hash}\n".encode("utf-8"))
    return h.hexdigest()


# ── Seal writer ───────────────────────────────────────────────────────────────

def write_seal(
    session_dir: Path,
    archive_path: Path,
    manifest_path: Path,
) -> dict:
    """Compute hashes and write seal.json + seal.txt into *session_dir*.

    Parameters
    ----------
    session_dir:    The mission session folder (contains manifest.json, etc.).
    archive_path:   The compressed .zip archive alongside the session folder.
    manifest_path:  Path to manifest.json inside session_dir.

    Returns
    -------
    The seal dict (same data written to seal.json).
    """
    created_at = datetime.now(timezone.utc).isoformat()

    mission_id = json.loads(manifest_path.read_text(encoding="utf-8")).get(
        "mission_id", session_dir.name
    )

    manifest_sha256 = sha256_file(manifest_path)
    archive_sha256 = sha256_file(archive_path)
    # Directory hash covers raw data files; seal + summary files are excluded.
    session_directory_sha256 = sha256_directory(session_dir)

    seal = {
        "mission_id": mission_id,
        "created_at": created_at,
        "manifest_sha256": manifest_sha256,
        "archive_sha256": archive_sha256,
        "session_directory_sha256": session_directory_sha256,
        "seal_version": SEAL_VERSION,
    }

    # ── seal.json ─────────────────────────────────────────────────────────────
    (session_dir / "seal.json").write_text(
        json.dumps(seal, indent=2), encoding="utf-8"
    )

    # ── seal.txt ──────────────────────────────────────────────────────────────
    seal_txt = (
        f"SPECIAL AGENT OPS MISSION SEAL\n"
        f"Mission ID: {mission_id}\n"
        f"Created At: {created_at}\n"
        f"Manifest SHA256: {manifest_sha256}\n"
        f"Archive SHA256: {archive_sha256}\n"
        f"Session Directory SHA256: {session_directory_sha256}\n"
        f"Seal Version: {SEAL_VERSION}\n"
    )
    (session_dir / "seal.txt").write_text(seal_txt, encoding="utf-8")

    return seal
